language: python
python:
    - "3.6"

install:
    - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install -r requirements.txt; fi
    - python setup.py install

script:
    - pytest py/picca/test/test_cor.py -s
